### PR TITLE
Fix/additions for 3.2 Crafter Blue Scrip Shop + RB_CN data separation

### PR DESCRIPTION
**Pull request by 7h3Cub3**
- Fixed Idyllshire NPC's location for turn-in/scrip shop (scrip shop npc was too far sometimes)
- Fixed and added relevant pre-3.2 blue scrip crafter items
- Added relevant 3.2 blue scrip crafter items
- Separated data between RB_CN client and the others (RB_CN not fixed, still old datas)

### CODE REVIEW

**Comment by 7h3Cub3** [comment]
Hope this time everything is fine, will not be able to test RB_CN but since i cloned the previous datas, should work just fine :)

**Comment by 7h3Cub3** [comment]
Humm... is there an issue with my pulling request ?

**Comment by mastahg** [comment]
Haven't had time to test it on cn servers

**Comment by 7h3Cub3** [comment]
Oh ok, thought there was something wrong and was willing to fix it :) alright then, take your time :) i have something else coming still doing testing but it's coming along ! (standalone skywatcher mod)

Cheers

**Comment by 7h3Cub3** [comment]
I asked to someone i know from the RB discord channel to test out with the CN, and he told me everything was working well (turn-in, buying scrip stuff), just so you know :) there seems to be an issue with the npc location for RB_CN (something about being stuck in a wall) i'm gonna see if i can fix it, and i'll push new coords ! Cheers.

**Comment by mastahg** [comment]
I didn't have time to remesh the cn stuff until just now. Should no longer be running into walls.

**Comment by 7h3Cub3** [comment]
Alright, i had a new set of coords otherwise :) i have severals chinese people that tested my modification + the new set of coords, and they said all was working well :)

**Comment by ghost** [comment]
When will we have this merged to Exbuddy?

**Pull request merged**
