### PR TITLE
Updates for CN patch 3.3

### PR DESCRIPTION
**Pull request by ghost**
Fixed the turnincollectable function for CN server.
Fixed the problem with ExFishTag when some Chinese player plays NA server on Windows in Chinese language.
And sorry for that I didn't make the correct pull request yesterday.

### CODE REVIEW

**Comment by Mattygs6** [comment]
Is there a bug with the localization of the regular expressions? 

ExBuddy/OrderBotTags/Fish/ExFishTag.cs ??

**Comment by ghost** [comment]
yes, those chinese players who play on NA server cannot keep the fish correctly. The regex won't work if the player is on NA server and Windows with a Chinese language. So different regex should be used based on RebornbuddyCN or not.

**Comment by mastahg** [comment]
You cannot play on the na servers with the game locale set to Chinese, and the windows locale is not a factor.

I think you mean to say that the RBCN client needs a different regex.

**Comment by ghost** [comment]
yes, that's what I mean, RBCN needs a different regex.

**Comment by Mattygs6** [comment]
In that case... can't we just have it updated in the .resx file?

**Comment by ghost** [comment]
Sorry if I have confused you. 
If the player is using Chinese Windows and RebornBuddy for NA Server, the regex being used will still be the Chinese one (base on windows locale), so it cannot keep the fish correctly.

I'm not sure how many chinese players are botting on NA server, but this applies to some of my friends.

**Comment by Mattygs6** [comment]
Ok.. i see the issue now..
zh-cn windows.
RB NA
EN game text.

I have a few ideas.
1. Each user should be able to change their Region & Language options in windows to be United States/English.
2. A plugin could theoretically change the thread culture, back to en or en-US in RB, but i do not know if this would work after startup.
3. Maybe we could get RB to add a localization config setting that would force a specific culture for it to run as.

**Comment by ghost** [comment]
The first option may cause problem with other applications running on Windows.

I'm not sure if other two are possible.

**Pull request closed without merging**
