### PR TITLE
Fix/additions for 3.2 Crafter Blue Scrip Shop

### PR DESCRIPTION
**Pull request by 7h3Cub3**
- Fixed Idyllshire NPC location (sometimes it wasn't at range of the scrip shop NPC)
- Fixed and added pre-3.2 crafter blue scrip items
- Added post-3.2 new crafter blue scrip items.

### CODE REVIEW

**Comment by mastahg** [comment]
As I said in the other PR this will break the system for chinese users and cannot be merged as is.

**Comment by 7h3Cub3** [comment]
Ok, what do you think need to be fixed for the chinese people ?

**Comment by mastahg** [comment]
If the changes are going to be so wide spread to the enums and the class then the entire class and enum should be duplicated and wrapped in #if RB_CN oldstuff #else newstuff #endif

**Comment by 7h3Cub3** [comment]
Oh i see the chinese aren't yet at 3.2, that makes sense ! so i need to make what you did for idyllshire NPC position with old/new stuff 

Roger i will close this PR for now, and work on that, i sadly can't test it but we'll see for that after !

Thanks for your keen insight into that matter, i just wasn't aware of that difference.

**Pull request closed without merging**
